-- Drop existing tables to avoid conflicts
DROP TABLE IF EXISTS contact_person CASCADE;
DROP TABLE IF EXISTS student_lessons CASCADE;
DROP TABLE IF EXISTS student_payment CASCADE;
DROP TABLE IF EXISTS sibling CASCADE;
DROP TABLE IF EXISTS discount CASCADE;
DROP TABLE IF EXISTS instrument_rental CASCADE;
DROP TABLE IF EXISTS rental_price_history CASCADE;
DROP TABLE IF EXISTS instrument CASCADE;
DROP TABLE IF EXISTS lesson_price_history CASCADE;
DROP TABLE IF EXISTS individual_lesson CASCADE;
DROP TABLE IF EXISTS group_lesson CASCADE;
DROP TABLE IF EXISTS ensembles_lesson CASCADE;
DROP TABLE IF EXISTS lesson CASCADE;
DROP TABLE IF EXISTS person_phone CASCADE;
DROP TABLE IF EXISTS phone CASCADE;
DROP TABLE IF EXISTS person_email CASCADE;
DROP TABLE IF EXISTS email CASCADE;
DROP TABLE IF EXISTS person_address CASCADE;
DROP TABLE IF EXISTS address_info CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS instructor_salary CASCADE;
DROP TABLE IF EXISTS instructor CASCADE;
DROP TABLE IF EXISTS system_config CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TYPE IF EXISTS difficulty CASCADE;

-- Skapa ENUM-typen för difficultyLevel
CREATE TYPE difficulty AS ENUM ('beginner', 'intermediate', 'advanced');

-- Create the person table
CREATE TABLE person (
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_number CHAR(12) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

-- Create the email table
CREATE TABLE email (
    email_id CHAR(10) NOT NULL PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE
);

-- Create the person_email table
CREATE TABLE person_email (
    person_id INT NOT NULL,
    email_id CHAR(10) NOT NULL,
    PRIMARY KEY (person_id, email_id),
    FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE,
    FOREIGN KEY (email_id) REFERENCES email(email_id) ON DELETE CASCADE
);

-- Create the phone table
CREATE TABLE phone (
    phone_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_no VARCHAR(200) NOT NULL UNIQUE
);

-- Create the person_phone table
CREATE TABLE person_phone (
    person_id INT NOT NULL,
    phone_id INT NOT NULL,
    PRIMARY KEY (person_id, phone_id),
    FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE,
    FOREIGN KEY (phone_id) REFERENCES phone(phone_id) ON DELETE CASCADE
);

-- Create the address_info table
CREATE TABLE address_info (
    address_id VARCHAR(100) NOT NULL PRIMARY KEY,
    zip CHAR(5) NOT NULL,
    street VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL
);

-- Create the person_address table
CREATE TABLE person_address (
    person_id INT NOT NULL,
    address_id VARCHAR(100) NOT NULL,
    PRIMARY KEY (person_id, address_id),
    FOREIGN KEY (person_id) REFERENCES person(person_id)ON DELETE CASCADE, 
    FOREIGN KEY (address_id) REFERENCES address_info(address_id)
);

-- Create the student table
CREATE TABLE student (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL,
    number_of_siblings INT,
    skill_level VARCHAR(100),
    FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE
);

-- Create the contact_person table
CREATE TABLE contact_person (
    contact_person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL,
    student_id INT NOT NULL,
    relation VARCHAR(100) NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE
);

-- Create the sibling table
CREATE TABLE sibling (
    sibling_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE
);

-- Create the discount table
CREATE TABLE discount (
    discount_id VARCHAR(50) NOT NULL PRIMARY KEY,
    discount_rate DECIMAL(10, 2) NOT NULL,
    student_id INT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE
);

-- Create the system_config table
CREATE TABLE system_config (
    config_type VARCHAR(50) NOT NULL PRIMARY KEY,
    config_value INT NOT NULL
);

-- Insert default system constraints
INSERT INTO system_config (config_type, config_value)
VALUES
    ('max_rental_duration_months', 12),
    ('max_active_rentals_per_student', 2);

-- Create the instructor table
CREATE TABLE instructor (
    instructor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL,
    scheduled_time_slot TIMESTAMP NOT NULL,
    lesson_type VARCHAR(100) NOT NULL,
    teach_ensembles BOOLEAN NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE CASCADE
);

-- Create the instructor_salary table
CREATE TABLE instructor_salary (
    salary_payment_id VARCHAR(50) NOT NULL PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL,
    date_of_payment DATE NOT NULL,
    instructor_id INT NOT NULL,
    FOREIGN KEY (instructor_id) REFERENCES instructor(instructor_id) ON DELETE CASCADE
);

-- Create the lesson_price_history table
CREATE TABLE lesson_price_history (
    lesson_price_id VARCHAR(50) NOT NULL PRIMARY KEY,
    skill_level_price INT NOT NULL,
    lesson_type_price INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current BOOLEAN NOT NULL,
    CONSTRAINT chk_end_date_after_start CHECK (end_date > start_date)
);

-- Create the lesson table
CREATE TABLE lesson (
    lesson_id VARCHAR(50) NOT NULL PRIMARY KEY,
    lessonType VARCHAR(50) NOT NULL,
    startDate DATE NOT NULL,
    duration TIME NOT NULL,
    instrumentType VARCHAR(50),
    difficultyLevel difficulty NOT NULL,
    lesson_price_id VARCHAR(50) REFERENCES lesson_price_history(lesson_price_id) ON DELETE CASCADE,
    instructor_id INT NOT NULL REFERENCES instructor(instructor_id) ON DELETE CASCADE
);

-- Create the student_lessons table
CREATE TABLE student_lessons (
    lesson_id VARCHAR(50) NOT NULL,
    student_id INT NOT NULL,
    PRIMARY KEY (lesson_id, student_id),
    FOREIGN KEY (lesson_id) REFERENCES lesson(lesson_id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE
);

-- Create lesson types
CREATE TABLE individual_lesson (
    lesson_id VARCHAR(50) NOT NULL PRIMARY KEY,
    timeSlot TIME NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES lesson(lesson_id) ON DELETE CASCADE
);

CREATE TABLE group_lesson (
    lesson_id VARCHAR(50) NOT NULL PRIMARY KEY,
    max_students INT NOT NULL,
    min_students INT NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES lesson(lesson_id) ON DELETE CASCADE
);

CREATE TABLE ensembles_lesson (
    lesson_id VARCHAR(50) NOT NULL PRIMARY KEY,
    genre VARCHAR(10) NOT NULL,
    max_students INT NOT NULL,
    min_students INT NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES lesson(lesson_id) ON DELETE CASCADE
);

-- Create the instrument table
CREATE TABLE instrument (
    instrument_id VARCHAR(50) NOT NULL PRIMARY KEY,
    instrument_type VARCHAR(100) NOT NULL,
    instrument_brand VARCHAR(100) NOT NULL,
    available_stock INT NOT NULL,
    lesson_id VARCHAR(50),
    FOREIGN KEY (lesson_id) REFERENCES lesson(lesson_id) ON DELETE CASCADE
);

-- Create the rental_price_history table
CREATE TABLE rental_price_history (
    rental_price_id VARCHAR(50) NOT NULL PRIMARY KEY,
    instrument_id VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current BOOLEAN NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (instrument_id) REFERENCES instrument(instrument_id) ON DELETE CASCADE
);

-- Create the instrument_rental table
CREATE TABLE instrument_rental (
    rental_id VARCHAR(100) NOT NULL PRIMARY KEY,
    rental_start_time TIMESTAMP NOT NULL,
    lease_expiry_time TIMESTAMP NOT NULL,
    rental_price_id VARCHAR(50) NOT NULL,
    instrument_id VARCHAR(50) NOT NULL,
    student_id INT NOT NULL,
    FOREIGN KEY (rental_price_id) REFERENCES rental_price_history(rental_price_id) ON DELETE CASCADE,
    FOREIGN KEY (instrument_id) REFERENCES instrument(instrument_id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE
);

-- Create the student_payment table
CREATE TABLE student_payment (
    payment_id VARCHAR(50) NOT NULL PRIMARY KEY,
    payment_date DATE NOT NULL,
    discount_id VARCHAR(50),
    rental_id VARCHAR(100),
    student_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (discount_id) REFERENCES discount(discount_id) ON DELETE CASCADE,
    FOREIGN KEY (rental_id) REFERENCES instrument_rental(rental_id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE
);
